### ISSUE TITLE
Support for external requirements.txt

### ISSUE THREAD

**Issue by lupino3** [xvik/gradle-mkdocs-plugin#11]
Hello,
I am wondering if it would be possible to use an external `requirements.txt` file to specify the Python dependencies.

This would allow bots that upgrade Python project versions to do upgrades that are picked up by this plugin.

For example, Dependabot opened this PR for my project: https://github.com/EduMIPS64/edumips64/pull/564. The PR updates the Sphinx version in the `requirements.txt` file, but of course the bot doesn't understand that I encode the dependencies in the `build.gradle.kts` file.

It would be awesome to be able to say "read deps from this file" to get the best of both worlds (auto-update and Gradle/Python integration).

**Comment by xvik** [comment]
Hello!
I will look at this later (need to finish other things first). Should be pretty simple to support it.

But requirements file would be restricted to exact version syntax (==) only.

And it would be done in use-python plugin (mkdocs will inherit this feature automatically).

**Comment by lupino3** [comment]
Thanks a lot @xvik ! Of course no hurry, it's not urgent at all. Thanks

**Comment by zubri** [comment]
Hi,

I'm looking for the same. In my case is to install other plugins for mkdocs, such as:
https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#global-password-protection

Otherwise the mkdocsServe or mkdocsBuild tasks fails with:
 ERROR    -  Config value: 'plugins'. Error: The "encryptcontent" plugin is not installed
if the plugin is not pre-installed with pip.

Regards

**Comment by xvik** [comment]
Mkdocs-encryptcontent-plugin could be [installed from pip](https://xvik.github.io/gradle-mkdocs-plugin/latest/guide/pip/) already:

```groovy
python.pip 'mkdocs-encryptcontent-plugin:2.3.1'
```

There is also a way to install plugins [directly from git](https://xvik.github.io/gradle-use-python-plugin/latest/guide/pip/#vcs-pip-modules) when required.

In general, requirements file support is already implemented in [python plugin](https://github.com/xvik/gradle-use-python-plugin) together with docker support, but not yet released. There would be a way to configure native requirements behaviour (by default, it would be restricted)

**Comment by lupino3** [comment]
Hey @xvik, would it be possible for you to release a new version of `gradle-use-python-plugin`? This new feature be very helpful to integrate automatic Python dependency management. Thanks!

**Comment by xvik** [comment]
I'm strill finalizing docker support implementation (many pitfalls to consider). But, hopefully, soon I will, of course, release it (maybe this weekend).
And soon after that there will be mkdocs plugin release (with required improvements for docker support).

**Comment by lupino3** [comment]
Thank you!

**Comment by zubri** [comment]
For the encryption plugin, I've just notice `gradle-mkdocs-plugin` uses the `gradle-use-python-plugin` and from that one I just needed to add this my build.gradle

python {
	pip 'mkdocs-encryptcontent-plugin:2.3.1'
}

Regards and thanks for these very useful plugins

**Comment by lupino3** [comment]
Hey @xvik, just got `gradle-use-python-plugin` version 3 and the new requirements support works like a charm! Finally I have automatic dependency updates for python as well! E.g. https://github.com/EduMIPS64/edumips64/pull/712. Closing the issue, thank you!
