### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [xvik/gradle-mkdocs-plugin#12]
Is this supported? I can't see what version of squidfunk mkdocs your plugin is using.

https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=dark#color-palette-toggle

**Comment by JavierSegoviaCordoba** [comment]
Do you have an ETA? Not sure if you are interesting in add Renovate for example to get automatic pull requests for those dependencies so you haven't to do this work manually.

**Comment by xvik** [comment]
It is not so simple to do automatic dependency updates there because default pip versions are defined in code (dependabot can't handle this). 

Ok, let's do it like this: I'll update dependencies this week and if everything will be alright will release a new version.
Initially, I was going to release the python plugin first and look for documentation version selection, but I will not do it too soon, so a quick release should be a good compromise.

**Comment by JavierSegoviaCordoba** [comment]
I think a way can be codegen the versions in build folder when Gradle sync. This codegen will pick the original versions from something which is compatible with Renovate. I haven't developed python so I don't know how to use dependencies there, but the standard ways should be compatible with Renovate for sure.

**Comment by xvik** [comment]
Dark mode is supported in the latest [2.2.0 release](https://github.com/xvik/gradle-mkdocs-plugin/releases). For configuration see [migration page](https://xvik.github.io/gradle-mkdocs-plugin/2.2.0/about/migration/#dark-theme)

I was also able to add support for [documentation version switcher component](https://xvik.github.io/gradle-mkdocs-plugin/2.2.0/about/migration/#version-switcher), but without mike tool usage (plugin now implements all its features natively, allowing [aliases usage](https://xvik.github.io/gradle-mkdocs-plugin/2.2.0/about/migration/#documentation-aliases))

New [examples page](https://xvik.github.io/gradle-mkdocs-plugin/2.2.0/examples/) demonstrates common plugin configurations.

>I think a way can be codegen the versions in build folder when Gradle sync. This codegen will pick the original versions from something which is compatible with Renovate. I haven't developed python so I don't know how to use dependencies there, but the standard ways should be compatible with Renovate for sure.

Most likely, I will implement something like this, but much later (plugin update already took too much time). There is an issue for python requirements files support (#11) and automatic package updates would be part of it.
