### ISSUE TITLE
Plugin no longer works on java 8

### ISSUE THREAD

**Issue by xvik** [xvik/gradle-mkdocs-plugin#13]
The plugin is now failing on java 8:

```
An exception occurred applying plugin request [id: 'ru.vyarus.mkdocs', version: '2.1.1']
> Failed to apply plugin 'ru.vyarus.mkdocs'.
   > Could not create plugin of type 'MkdocsPlugin'.
      > Could not generate a decorated class for type MkdocsPlugin.
         > org/eclipse/jgit/errors/RepositoryNotFoundException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This is due to transitive dependencies:

```
\--- ru.vyarus.mkdocs:ru.vyarus.mkdocs.gradle.plugin:2.1.1
     \--- ru.vyarus:gradle-mkdocs-plugin:2.1.1
          +--- ru.vyarus:gradle-use-python-plugin:2.3.0
          \--- org.ajoberstar:gradle-git-publish:3.0.0
               \--- org.ajoberstar.grgit:grgit-core:latest.release -> 4.1.0
                    \--- org.eclipse.jgit:org.eclipse.jgit:latest.release -> 6.0.0.202111291000-r
                         +--- com.googlecode.javaewah:JavaEWAH:1.1.13
                         \--- org.slf4j:slf4j-api:1.7.30
```

Will try to release the fix ASAP.

**Comment by xvik** [comment]
Workaround:
```
buildscript {
    configurations.classpath {
        resolutionStrategy {
            force 'org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r'
        }
    }
}
```
Put it at the top of `build.gradle`

**Comment by AlexanderStohr** [comment]
> Workaround:
> 
> ```
> buildscript {
>     configurations.classpath {
>         resolutionStrategy {
>             force 'org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r'
>         }
>     }
> }
> ```
> 
> Put it at the top of `build.gradle`

tried it but failed for me. (maybe it depends on the version of gradle or because i am having grgit and mkdocs in the same project - felt like i understood it sufficiently, but there might be more complexity somewhere under the hood.)

hoping for (patch-level) updated packages seeing release to fix that.

**Comment by xvik** [comment]
> there is a fix approach already in progress - solving the dependencies in the underlying packages. [apache/kafka#11554](https://github.com/apache/kafka/pull/11554)

Yes, forcing exact versions is the only way to fix it.

> tried it but failed for me.

I used this workaround with gradle 6.9: https://github.com/xvik/dropwizard-guicey/blob/master/build.gradle#L1

Anyway, I hope to release a new version today.

**Comment by AlexanderStohr** [comment]
found a temporary solution for my special setup:
downgraded from grgit 4.1.0 to 4.0.2 - but planning already for a later upgrade to 4.1.1 when it comes out.

reason for complication in my special setup:
had a base folder with just a few code checkers plus a sub folder with a second build.gradle that was responsible for mkdocs features.
had to add the version selection to both of these files - then it ran again as desired.

**Comment by JavierSegoviaCordoba** [comment]
This is strange, I updated jgit and I am using java 8 in some projects

**Comment by xvik** [comment]
Hotfix [version 2.1.2 released](https://github.com/xvik/gradle-mkdocs-plugin/releases/tag/2.1.2).
There would be another release soon (probably this week) with updated default mkdocs packaes versions (released only pure hotfix now because the recent mkdocs 1.2.3 contains some breaking changes)

**Comment by AlexanderStohr** [comment]
now works for me with latest grgit 4.1.1
