### ISSUE TITLE
Relative URL in nav doesn't find MD file.

### ISSUE THREAD

**Issue by heshamMassoud** [xvik/gradle-mkdocs-plugin#2]
I want to use in the nav an MD file which is in the parent directory of the `sourcesDir` (as described [here](https://www.mkdocs.org/user-guide/configuration/#nav)]) but mkDoc doesn't see it somehow. 

So 
- My `sourcesDir` is `docs` which is in the root directory. 
- I have an MD file `README.md` which is also in the root directory.
- To use this in the nav, I set in the [`mkdocs.yml`](https://github.com/commercetools/commercetools-sync-java/blob/create-doc-pages/mkdocs.yml#L48):
```yaml
nav:
  - Overview: ../README.md
```

However, when I get the error:
```bash
A relative path to '../README.md' is included in the 'nav' configuration, which is not found in the documentation files
```

**Comment by xvik** [comment]
Sorry, can't help you. My best guess is that mkdocs considers 'docs' as site root and so build site hierarchy accordingly. When you add relative page outside of root dir, mkdocs is confused (how could it build an url for this relative path).

[Source](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/nav.py#L142) isn't much help.

You can try to ask in the mkdocs community (it's pure mkdocs issue).
