### ISSUE TITLE
Compatibility matrix section is outdated

### ISSUE THREAD

**Issue by onkarjoshi** [xvik/gradle-mkdocs-plugin#25]
Would it make sense to update the compatibility matrix to clarify Java 17 and Gradle 7.x compatibility?

https://github.com/xvik/gradle-mkdocs-plugin#compatibility

**Comment by xvik** [comment]
Have you tried it? I just didn't try it yet.

**Comment by onkarjoshi** [comment]
I haven't. Was trying to find out about known compatibility issues before attempting to upgrade.

**Comment by xvik** [comment]
Did a quick check runing tests with jdk 17 and it seems to be working.

I can't add jdk17 into CI builds because only gradle 7.4 is compatible with it, but plugin built with gradle 7.x loose backwards compatibilty (can't be used on gradle < 7) and so project stuck on gradle 6.9 for now.

**Comment by xvik** [comment]
Closing as there is no knowing issues. Please reopen or create a new issue if there would be any problems
