### ISSUE TITLE
Example entry `into "\${mkdocs.resolveDocPath()}/javadoc"` creates a folder called `${mkdocs.resolveDocPath()}`

### ISSUE THREAD

**Issue by michael-newsrx** [xvik/gradle-mkdocs-plugin#41]
Trying to include Javadoc.

When using provided configuration example a folder is created literally named `${mkdocs.resolveDocPath()}`.

If I specify just `into "javadoc"` it works as expected.

```groovy
gitPublish.contents {
    from(javadoc) {
        // need to use resolveDocPath because by default it's a template 
        into "\${mkdocs.resolveDocPath()}/into "\${mkdocs.resolveDocPath()}/javadoc"javadoc"
    }
}

// dependency will NOT be set automatically by copySpec above
gitPublishReset.dependsOn javadoc
```

**Comment by xvik** [comment]
Oh, of course, it should be

```
into "${mkdocs.resolveDocPath()}/javadoc"
```

('$' without escaping instead of '\$').

I copied example directly from test where build file is declared in string and so escape is required and forgot to remove it in real doc. I'll fix the doc. 
Thank you!

**Comment by michael-newsrx** [comment]
Probably need to add a comment about how mkdocs.resolveDocPath() can return null.

**Comment by xvik** [comment]
This might happen when version is not declared in project or `mkdocs.publish.docPath` explicitly set to null. 
I'll add checks to fail with an error in this case instead of continuing with null.

**Comment by xvik** [comment]
I was a bit wrong: null returned only when multi-version publishing is switched off (`mkdocs.publish.docPath=null`). In case of not defined version, version would be `unspecified`, but not null.

Updated javadoc sample in doc to warn about null in case of single version mode (doc site not yet published)

**Comment by michael-newsrx** [comment]
Why not change it to have a fallback value of `.`? This way the example evaluated result becomes `./javadoc`.

**Comment by xvik** [comment]
Hmm, interesting idea, I'll try it. Thank you!
