### ISSUE TITLE
Mkdocs plugin assumes a valid git working tree in all cases

### ISSUE THREAD

**Issue by derekm** [xvik/gradle-mkdocs-plugin#45]
If Mkdocs plugin is enabled, but source code is used outside of git, for example after `git archive`, then all gradle tasks will fail as the Mkdocs plugin fails.

Mkdocs plugin should not fail all gradle tasks just because the source code isn't in a git clone.

Mkdocs plugin looks up publish.repoUri, which fails if there is no git metadata or if a `config` directory exists at the root of the project.

**Comment by xvik** [comment]
Could you please post the error itself here (if possible, run gradle with `--stacktrace` option). And, please, describe steps to simulate this situatuation (is it multi-module project?).

Plugin works when there is no initialized git in the project (it should be the case for git archive). Anyway, there is only one place that can fail - git origin detection appeared just after project initialization. But I need a guide to reproduce the problem to be sure

There should be a workaround: you can specify `mkdocks.publish.repoUrl` manually and plugin will not try to auto-detect origin and so should stop failing the build.

**Comment by xvik** [comment]
In the new version [3.0.0](https://github.com/xvik/gradle-mkdocs-plugin/releases/tag/3.0.0) there should be no problem with it.

Moreover, now it is possible to avoid publication tasks (and git related staff) at all with new lightweight plugin version `ru.vyarus.mkdocs-build`.

Closing this, please reopen if issue will appear again
