### ISSUE TITLE
checkPython task fails with Java 11

### ISSUE THREAD

**Issue by dcp65** [xvik/gradle-mkdocs-plugin#5]
This could be a bug with the mkdocs plugin, the [use-python-plugin](https://github.com/xvik/gradle-use-python-plugin), Java or Gradle. 

Using Gradle 6.1.1

To reproduce

Create an empty project called `python_test` with the following `build.gradle`:

```
plugins {
    id 'ru.vyarus.mkdocs' version '2.0.0'
}

mkdocs {
    sourcesDir = 'src'
    strict = true
    buildDir = 'build'
    updateSiteUrl = true

    publish {
        docPath = ''
    }
}
```

Run `./gradlew mkdocsInit` to create a boilerplate project structure.

With `$JAVA_HOME` set to JDK 1.8, run `./gradlew checkPython`. 

As expected, a virtual environment is created in the `.gradle` folder of the project:

` Using python 3.7.3 from /Users/dcp/projects/python_test/.gradle/python 
  (/Users/dcp/projects/python_test/.gradle/python/bin/python`

Change `$JAVA_HOME` to point to Java 11.
Run `./gradlew checkPython` again. 

Result:

`Execution failed for task ':checkPython'.
 java.nio.file.NoSuchFileException: /Users/dcp/.gradle/daemon/6.1.1/.gradle/python/bin`

Gradle is looking for Python in the `.gradle` directory of the user's home directory. It should be looking in the project folder.

**Comment by xvik** [comment]
Agree looks like python plugin bug (and quite silly). I'll look it closer a bit later.
