### ISSUE TITLE
Upgrade to Mkdocs 1.4.2

### ISSUE THREAD

**Issue by glureau** [xvik/gradle-mkdocs-plugin#57]
The [1.4.2](https://github.com/mkdocs/mkdocs/releases/tag/1.4.2) provides bugfixes that I'd love to use.

If it's just about creating a PR, updating the version and running the tests, I can probably do that (not sure I can go beyond that point tho).

**Comment by xvik** [comment]
You can always [update mkdocs in your build](https://xvik.github.io/gradle-mkdocs-plugin/latest/guide/pip/):

```groovy
python.pip 'mkdocs:1.4.2'
```

(probably, I should refrase the docs to highlight that it is ok to update packages without waiting for plugin release - plugin just provides good defaults for quickstart)

mkdocs-material 9 is not yet released, so if there are no very important fixes in mkdocs 1.4.2  I would prefer to wait for a new material version. 
Its not hard to release a new version, but I prefer to do it for a good reason (e.g. bug affecting many users or major package release, changing configs or introducting new important features).

**Comment by xvik** [comment]
[released 4.0.0](https://github.com/xvik/gradle-mkdocs-plugin/releases/tag/4.0.0) with mkdocs 1.5.3 by default (today 4.0.1 would be released with non-strict mode fix)
