### ISSUE TITLE
How to disable gradle-git-publish

### ISSUE THREAD

**Issue by Austinreedthomas** [xvik/gradle-mkdocs-plugin#9]
This is not a feature I would like to use but it's a direct dependency.

**Comment by xvik** [comment]
And what problem do you have with it?

**Comment by xvik** [comment]
Just checked the code and there is no way to disable git-publish plugin currently.
But git-publish plugin is used only by mkdocsPublish task and so it shouldn't bother you if you don't call mkdocsPublish (assuming you'll use your own custom task for publication or, maybe, no publication at all).

I could look to make this plugin optional, but I don't see a good reason for it now (simply not using provided publication task looks good enough for me). If there are any issues with it please tell me.

**Comment by Austinreedthomas** [comment]
Okay thanks for checking and getting back to me so quickly! Feel free to close this issue.
